### ISSUE TITLE
How to set the random seed function?

### ISSUE THREAD

**Issue by Changhao21** [ggsDing/Bi-SRNet#18]
Hello, this is a very meaningful work, but I have a question: may I ask you how to set the random seed? I tried to add different random seed functions before the training code, but the results of each training still changed, is it convenient for you to share the random seed functions in this project?

**Comment by ggsDing** [comment]
Hi, thanks for following. I do not remember setting any random seed.

**Comment by Changhao21** [comment]
Ok, thanks for answering.
