### ISSUE TITLE
运行train_SCD.py报错MemoryError

### ISSUE THREAD

**Issue by Jackoldwolf** [ggsDing/Bi-SRNet#19]
![image](https://user-images.githubusercontent.com/58628366/221135881-eef573c7-ef6e-4ad1-8565-15f84c8a5224.png)
你好！运行train_SCD.py时加载完数据后执行train函数报MemoryError，请问是什么问题？

**Comment by ggsDing** [comment]
maybe it means out of RAM

**Comment by Jackoldwolf** [comment]
Thanks！
