### ISSUE TITLE
In Eval_SCD.py 

### ISSUE THREAD

**Issue by choidaedae** [ggsDing/Bi-SRNet#24]
Hello, I read this issue and I'm not going well with it, too: 
https://github.com/ggsDing/Bi-SRNet/issues/21

Can you explain in more detail what parts of the code I should change?

**Comment by ggsDing** [comment]
> Hello, I read this issue and I'm not going well with it, too: #21
> 
> Can you explain in more detail what parts of the code I should change?

Replace the rgb_dir to index_dir in line 49, 50.

You are also welcome to check our latest work on SCD: [link](https://github.com/ggsDing/SCanNet).

**Comment by choidaedae** [comment]
Hello! Thank you for reply :) 

I solved this problem myself two days ago, and I remember that maybe this solution didn't solve the problem. The dimensions of the image array didn't match, so I kept the rgb directory, while at the same time loading the 'Color2Index' function in RS_ST.py, I used it and solved the problem. Is it okay to pull request for that part?

**Comment by ggsDing** [comment]
> 

The evaluation codes suppose that the input results are index predictions. There are options in 'pred_SCD.py' to control whether to output index predictions or RGB predictions.

**Comment by choidaedae** [comment]
I understood, Thx :)

**Comment by wangqingl** [comment]
> Hello! Thank you for reply :)
> 
> I solved this problem myself two days ago, and I remember that maybe this solution didn't solve the problem. The dimensions of the image array didn't match, so I kept the rgb directory, while at the same time loading the 'Color2Index' function in RS_ST.py, I used it and solved the problem. Is it okay to pull request for that part?

hello, how to deal with the question, could you give me some advice? thank you

**Comment by Perfuncotry** [comment]
> index_dir
Hello, I have tried many times recently but still haven't been able to solve this problem. How should I modify the code? I hope to receive your advice. I would be extremely grateful!
assert unique_set.issubset(set([0, 1, 2, 3, 4, 5, 6])), "unrecognized label number"
AssertionError: unrecognized label number

**Comment by ZhangQuan-wq** [comment]
Hello,I have set the four files like this:INFER_DIR1 = r'C:\Users\dell\Desktop\Bi_SRNet_main\Bi_SRNet\pred_dir\im1_rgb'  # Inference path1
    INFER_DIR2 = r'C:\Users\dell\Desktop\Bi_SRNet_main\Bi_SRNet\pred_dir\im2_rgb'  # Inference path2
    LABEL_DIR1 = r'C:\Users\dell\Desktop\Bi_SRNet_main\Bi_SRNet\SECOND\Test\label1'  # GroundTruth path
    LABEL_DIR2 = r'C:\Users\dell\Desktop\Bi_SRNet_main\Bi_SRNet\SECOND\Test\label2'  # GroundTruth path
the files can be found, but the Lists are empty,why?Glob pattern for INFER_DIR1: C:\Users\dell\Desktop\Bi_SRNet_main\Bi_SRNet\pred_dir\im1_rgb*.png
Glob pattern for INFER_DIR2: C:\Users\dell\Desktop\Bi_SRNet_main\Bi_SRNet\pred_dir\im2_rgb*.png
Glob pattern for LABEL_DIR1: C:\Users\dell\Desktop\Bi_SRNet_main\Bi_SRNet\SECOND\Test\label1*.png
Glob pattern for LABEL_DIR2: C:\Users\dell\Desktop\Bi_SRNet_main\Bi_SRNet\SECOND\Test\label2*.png
Infer list1: []
Infer list2: []
Label list1: []
Label list2: []
No accuracy data available.
bn_hist: TP 0, FN 0, FP 0, TN 0
Accuracy = 0.000%
Mean IoU = 0.000
Sek = 0.000
Score = 0.000
0
change_ratio = 0.0000, SC_Precision = 0.0000, SC_Recall = 0.0000, F_scd = 0.0000
