### ISSUE TITLE
论文中LSC语义一致性损失

### ISSUE THREAD

**Issue by long123524** [ggsDing/Bi-SRNet#28]
![image](https://github.com/ggsDing/Bi-SRNet/assets/73996375/8d15c501-f98a-4577-957a-c759644054cd)
您好，按照nn.CosineEmbeddingLoss的损失定义，论文中的一致性损失，标签值是不是写反了呢？上面应该是0（未变化的情况），下面的公式是1（变化）。

**Comment by ggsDing** [comment]
这里的 yc 是跟代码保持一致，1是未变，0是变化。此处确实不太严谨，没有格外说明。代码实现是没问题的
