### ISSUE TITLE
may i ask for the second database?

### ISSUE THREAD

**Issue by DA-II** [ggsDing/Bi-SRNet#3]
i notice that in the paper you used second database to train network, but i did't found it, could you share it or give me a website?

**Comment by ggsDing** [comment]
It is released in this paper:
https://doi.org/10.1109/TGRS.2021.3113912

**Comment by AirHighway** [comment]
> It is released in this paper: https://doi.org/10.1109/TGRS.2021.3113912

Thanks for your reply, SECOND is a wonderful database.  I'm also interested in SCD, the lack of data is a big obstacles for me. Do you know some other data can be used in SCD? It would be a great honor if you could reply to me.

**Comment by ggsDing** [comment]
> 
Hi. There are also other ones, but I did not check if they are openly accessible. You can check the following papers to get access:
1. Hi-UCD: A large-scale dataset for urban semantic change detection in remote sensing imagery. arXiv preprint arXiv:2011.03247, 2020.
2. Multitask learning for large-scale semantic change detection[J]. Computer Vision and Image Understanding, 2019.

**Comment by DA-II** [comment]
Thanks
